# Generated by Django 4.2.3 on 2023-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_durstion',
            field=models.IntegerField(null=True),
        ),
    ]
