# Generated by Django 4.2.3 on 2023-07-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_video_time_durstion'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
