# Generated by Django 4.2.3 on 2023-07-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_language_course_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='language',
        ),
    ]
