# Generated by Django 4.2.3 on 2023-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_name_language_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cretificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
