# Generated by Django 4.2.3 on 2023-07-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_time_durstion_video_time_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cretificate',
            new_name='certificate',
        ),
    ]
